config/routes.rb
LandingPage::Application.routes.draw do

  root 'static_pages#index'
  
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]

  # GET /static_pages
  # GET /static_pages.json
  def index
    render layout: false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LandingPage</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing static_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pull up Bands</title>
 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
 <%= javascript_include_tag "application" %>
 <meta name="viewport" content="width=device-width; initial-scale=1.0;" />
  <style>
  body {
    background-image: url(<%= image_path("landing_page_bg.png") %>);
    background-position: center top;
    background-size: 100% auto;
    font-family: Arial, Helvetica, sans-serif;
  }
  #logo {
	  max-width:400px;
	  width:90%;
	  height:auto;

	}
	#title {
	  margin:10px;
	  padding:0;
	}
	#subtitle {
	  margin:5px;
	  padding:0;
	  margin-left:10px;
	}
	.proImg {
	  width:100%;
    height:100%;
  }
  .proOver {
    width:100%;
    height:100%;
    background-color:#ef4036;
    opacity:.5;
    color:white;
    position:absolute;
    top:0;
    left:0;
    z-index:10;
    font-size:30px;
    display:none;
    line-height:40px;
  }

.proImg:hover + .proOver {
    display: block;
  }

  .imageContainer {
    position: relative;
    width:100px;
	  height:84px;
	  border:1px solid black;
	  margin-left:auto;
	  margin-right:auto;
  }
  .atc {
	  background-color:#9edd56;
	  padding:3px;
	  font-weight:bold;
	  border:2px outset black;
	  border-radius:2px;
	  display:inline;
	  text-decoration:none;
	  color:black;
  }
  #proTable {
    width:440px;
  }
  
  #proTable td {
    width:50%;
    text-align:center;
    padding:10px;
    padding-top:10px;
    padding-bottom:10px;
    
  }
  .proTitle {
    padding:0;
    margin:0;
  }
  .proText {
    padding:0;
    margin:0;
    margin-bottom:5px;
  }
  .proPrice {
    font-weight:bold;
    display:inline;
  }
  #testimonial {
	  position:absolute;
	  bottom:0;
	  right:0;
	  width:200px;
	  background-color:white;
	  padding:10px;
	  background: rgba(230,230,230,.8);
  }
  #author {
	  text-align: right;
	  display: block;
	  font-size: 14px;
	  font-weight:bold;
	}
	#band_in_action {
	  display:none
	}
	#coupon {
	display:none;
	  background-color: #ffa;
	  border:5px dashed #000000;
	  border-radius:15px;
	  width:200px;
	  position:absolute;
	  top:0;
	  right:0;
	  margin:10px;
	  text-align:center;
-webkit-box-shadow: 10px 10px 10px 0px rgba(0,0,0,0.71);
-moz-box-shadow: 10px 10px 10px 0px rgba(0,0,0,0.71);
box-shadow: 10px 10px 10px 0px rgba(0,0,0,0.71);
	}
	#coupon_code {
	  font-weight:bold;
	  font-size:30px;
	  display:block;
	}
	.mobile_show {
	    display:none;
	  }
	@media only screen and (max-width: 450px){
	#proTable td {
	    display:block;
	    width:auto;
	    vertical-align:top;
	    margin-left:auto;
	    margin-right:auto;
	  }
	  #proTable {
	    width:90%;
	    padding:0;
	    margin:0;
	  }
	  .mobile_hide {
	    display:none;
	  }
	}
	@media only screen and (max-width: 640px){
	  #coupon {
	    position:relative;
      width:90%;
      margin-left:auto;
      margin-right:auto;
	  }
	  #band_in_action {
	    display: block;
	    width:90%;
	    margin-left:auto;
	    margin-right:auto;
	  }
	  body {
	    background-image: none;
	  }
	  #proTable {
	    width:90%;
	    margin-left:auto;
	    margin-right:auto;
	  }
	  #testimonial {
	    display:block;
	    position:relative;
	    width:90%;
	    margin-left:auto;
	    margin-right:auto;
	  }
	  .atc {
	    display:block;
	    max-width:200px;
	    width:70%;
	    margin-left:auto;
	    margin-right:auto;
	    padding:15px;
	    margin-top:5px;
	  }
	}
  </style>
</head>
<body>
<%= image_tag("black_logo.png", id: "logo") %>
<h1 id="title">Pull up bands</h1>
<h2 id="subtitle">Tough on Muscles, Easy on Wallets</h2>
<%= image_tag("landing_page_bg_mobile.png", id: "band_in_action") %>
<div id="coupon">
  <p>Use the code:
  <span id="coupon_code">CODE</span>
  <span id="coupon_description">description</span></p>
</div>
<table id="proTable">
  <tr>
    <td colspan='2' style="text-align:left">
      To find your perfect band combo, pick your weight below, and click the green button to add it to your cart.
    </td>
  </tr>
  <tr>
    <td>
      <h3 class="proTitle"> Athletes weighing <br class="mobile_hide">&lt; 140 lbs</h3>
      <a href="http://rubberbanditz.com/product/best-sellers/medium-heavy-resistance-band-combo">
        <div class="imageContainer">
          <%= image_tag("Medium-Heavy-Resistance-Band-Combo.jpg", class: "proImg") %>
          <div class="proOver">more info</div>
        </div>
      </a>
      <p class="proText">Medium, Heavy Combo</p>
      <p class="proPrice">$29.99 <a class="atc"href="http://rubberbanditz.com/store/cart?task=add-to-cart-anchor&cart66ItemId=26">Add to Cart</a></p>
    </td>
    <td>
<h3 class="proTitle">Athletes weighing <br class="mobile_hide">140 - 250 lbs</h3>
<a href="http://rubberbanditz.com/product/best-sellers/heavy-robust-resistance-band-combo">
<div class="imageContainer"><%= image_tag("Heavy-Robust-Resistance-Band-Combo.jpg", class: "proImg") %>
<div class="proOver">more info</div></div></a>
<p class="proText">Heavy, Robust Combo</p>
<p class="proPrice">$37.99 <a class="atc"href="http://rubberbanditz.com/store/cart?task=add-to-cart-anchor&cart66ItemId=27">Add to Cart</a></p>
</td>
</tr>
<tr>
<td>
<h3 class="proTitle">Athletes weighing <br class="mobile_hide">250 - 300 lbs</h3>
<a href="http://rubberbanditz.com/product/band-combinations/heavy-power-resistance-band-combo">
<div class="imageContainer"><%= image_tag("Heavy-Power-Resistance-Band-Combo.jpg", class: "proImg") %>
<div class="proOver">more info</div></div></a>
<p class="proText">Heavy, Power Combo</p>
<p class="proPrice">$48.99 <a class="atc"href="http://rubberbanditz.com/store/cart?task=add-to-cart-anchor&cart66ItemId=28">Add to Cart</a></p></td>
<td>
<h3 class="proTitle">Athletes weighing <br class="mobile_hide">300 lbs +</h3>
<a href="http://rubberbanditz.com/product/band-combinations/robust-power-resistance-band-combo">
<div class="imageContainer"><%= image_tag("Robust-Power-Resistance-Band-Combo.jpg", class: "proImg") %>
<div class="proOver">more info</div></div></a>
<p class="proText">Robust, Power Combo</p>
<p class="proPrice">$52.99 <a class="atc"href="http://rubberbanditz.com/store/cart?task=add-to-cart-anchor&cart66ItemId=29">Add to Cart</a></p></td>
</tr>
<tr>
<td colspan="2" style="padding:0;text-align:left;">
<p>For more information on pull up bands, read our <a href="http://rubberbanditz.com/info-center/pull-up-bands/">Pull up exercise page</a>, or visit our <a href="http://rubberbanditz.com/store/">full store</a>.</p>
</td>
</tr>
</table>

<div id="testimonial">
&quot;I recently received my bands, and was astounded to find out I 
could actually do pull-ups with them! Of course, eventually I 
hope to be able to pull up without the bands, but for now I am 
absolutely thrilled.&quot;
<div id="author">- Kathy</div>
</div>
</body>


</html>

app/views/static_pages/new.html.erb
<h1>New static_page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>